server:
  shutdown: graceful
  port: 8081
  servlet:
    context-path: /spring-docker
spring:
  sql:
    init:
      mode: always
# H2 in default mode
#  datasource:
#    url: jdbc:mysql://mysqldb/spring-docker
#    username: ${DB_USER:root}
#    password: ${DB_PASSWORD:password}
